# Site settings
title: Thomas Gallagher
email: gallagth@gmail.com
description: ""
baseurl: ""
url: "http://gallagth.github.io"
twitter_username: gallagth
github_username:  gallagth

# Build settings
markdown: kramdown
permalink: pretty
