# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Thomas Gallagher
tagline:          ''
description:      ''
url:              http://gallagth.github.io
baseurl:          /

author:
  name:           'Thomas Gallagher'
  url:            https://twitter.com/gallagth

paginate:         5
